services:
  - type: web
    name: mybank-web
    env: node
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      # - key: JWT_SECRET
      #   value: your_prod_secret_here
